# Generated by Django 4.2.23 on 2025-08-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('technology', models.TextField(max_length=100)),
                ('delivery_time', models.IntegerField(default=5)),
                ('price', models.PositiveIntegerField(default=1)),
                ('available', models.BooleanField(default=False)),
                ('images', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
