# Generated by Django 4.2.23 on 2026-02-24 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_images_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='project',
            new_name='product',
        ),
    ]
