# Generated by Django 4.2.23 on 2026-03-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_project_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload MP4 video file (max 100MB)', null=True, upload_to='product_videos/'),
        ),
        migrations.AddField(
            model_name='product',
            name='video_thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail image for video (optional)', null=True, upload_to='video_thumbnails/'),
        ),
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube or Vimeo URL (e.g., https://www.youtube.com/watch?v=...)', max_length=500, null=True),
        ),
    ]
