# Generated by Django 4.2.23 on 2026-03-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_video_file_product_video_thumbnail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='delivery_time',
        ),
        migrations.AddField(
            model_name='product',
            name='pages',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
